version: "3"

services:
  # this defines our webserver uses our sigsci-module
  # we only define it so it is attached to our fake network
  # it will be run a few times with different options manually
  #
  # The volumes spec is a bit weird.. this script is run in scripts/test but
  # needs stuff in ../../examples.  Consider moving.
  web:
    volumes:
      - ../..:/go/src/github.sigsci.in/engineering/sigsci-module-golang
    command: [ "go", "run", "/go/src/github.sigsci.in/engineering/sigsci-module-golang/examples/mtest/main.go" ]
