version: "3"
networks:
  mtest:

services:
  # this defines our webserver uses our sigsci-module
  # we only define it so it is attached to our fake network
  # it will be run a few times with different options manually
  #
  # The volumes spec is a bit weird.. this script is run in scripts/test but
  # needs stuff in ../../examples.  Consider moving.
  web:
    build: .
    networks:
      - mtest
    volumes:
      - ../..:/go/src/github.sigsci.in/engineering/sigsci-module-golang
    command: [ "go", "run", "/go/src/github.sigsci.in/engineering/sigsci-module-golang/examples/mtest/main.go" ]

  # agent
  agent:
    image: 803688608479.dkr.ecr.us-west-2.amazonaws.com/local-dev/sigsci-agent:latest
    command: [ "-rpc-address", "9090", "-debug-rpc-test-harness", "-debug-standalone", "3" ]
    networks:
      - mtest

  # mtest
  # we define the module-tester but don't start it (via command: /bin/true)
  #
  mtest:
    image: 803688608479.dkr.ecr.us-west-2.amazonaws.com/local-dev/module-testing:latest
    networks:
      - mtest
    depends_on:
      - web
      - agent
    environment:
      - DISABLE_HTTP_OPTIONS=1
      - DISABLE_NOCOOKIE=1
      - MTEST_BASEURL=web:8085
      - MTEST_AGENT=agent:12345
    command: [ "/bin/wait-for", "web:8085", "--", "/bin/mtest", "-test.v" ]
