name: Update release db
on: 
  release:
    types: [edited]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update metadata
        run: |
          ls ./scripts/
          ./scripts/update-release-metadata.py sigsci-module-golang ${{ github.ref }}
